AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Content Analysis - Deploys the AWS Content Analysis Application

Parameters:
  MieStackName:
    Description: Name of the Media Insights Engine framework stack
    Type: String
  AdminEmail:
    Description: Email address of the Content Analysis Administrator
    Type: String
  ElasticSearchNodeSize:
    Description: "The node type to be provisioned for the Elasticsearch cluster"
    Type: String
    Default: "t2.small.elasticsearch"
    AllowedValues:
      - "t2.small.elasticsearch"
      - "m4.large.elasticsearch"
      - "m4.xlarge.elasticsearch"
      - "c4.large.elasticsearch"
      - "c4.xlarge.elasticsearch"
      - "r4.large.elasticsearch"
      - "r4.xlarge.elasticsearch"
  ShortUUID:
    Description: Uuid to use for uniquely naming step functions in  workflows
    Type: String
    Default: "0"

Mappings:
<<<<<<< HEAD:cloudformation/aws-content-analysis-use-existing-mie-stack.yaml
=======
  MediaInsightsEngine:
    Release:
      Version: "v2.0.3"
>>>>>>> ef8e22eb9e28d8057d207ce692c76279ca15d5b2:cloudformation/aws-content-analysis-create-new-mie-stack.yaml
  ContentAnalysisApp:
    SourceCode:
      S3Bucket: "%%BUCKET_NAME%%"
      CodeKeyPrefix: "content-analysis-solution/%%VERSION%%/code"
      TemplateKeyPrefix: "content-analysis-solution/%%VERSION%%/cf"
      WebsitePrefix: "content-analysis-solution/%%VERSION%%/code/website"

Resources:

  # Deploy Elasticsearch
  ContentAnalysisElasticsearchStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-elasticsearch.template"
      Parameters:
<<<<<<< HEAD:cloudformation/aws-content-analysis-use-existing-mie-stack.yaml
        AnalyticsStreamArn:
          Fn::ImportValue:
            !Sub "${MieStackName}:AnalyticsStreamArn"
        MieDataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
=======
        AnalyticsStreamArn: !GetAtt MieStack.Outputs.AnalyticsStreamArn
        MieDataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket
>>>>>>> ef8e22eb9e28d8057d207ce692c76279ca15d5b2:cloudformation/aws-content-analysis-create-new-mie-stack.yaml
        NodeType: !Ref ElasticSearchNodeSize

  # Deploy Auth stack

  ContentAnalysisAuthStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-auth.template"
      Parameters:
        AdminEmail: !Ref AdminEmail
<<<<<<< HEAD:cloudformation/aws-content-analysis-use-existing-mie-stack.yaml
        WorkflowApiId:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowApiId"
        DataplaneApiId:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneApiId"
        ElasticDomainArn: !GetAtt ContentAnalysisElasticsearchStack.Outputs.DomainArn
        DataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
=======
        WorkflowApiId: !GetAtt MieStack.Outputs.WorkflowApiRestID
        DataplaneApiId: !GetAtt MieStack.Outputs.DataplaneApiRestID
        ElasticDomainArn: !GetAtt ContentAnalysisElasticsearchStack.Outputs.DomainArn
        DataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket

  ContentAnalysisWebStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - ".s3."
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-web.template"
      Parameters:
        DataplaneEndpoint: !GetAtt MieStack.Outputs.DataplaneApiEndpoint
        WorkflowEndpoint: !GetAtt MieStack.Outputs.WorkflowApiEndpoint
        ElasticEndpoint: !GetAtt ContentAnalysisElasticsearchStack.Outputs.ElasticEndpoint
        DataplaneBucket: !GetAtt MieStack.Outputs.DataplaneBucket
        UserPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolId
        IdentityPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.IdentityPoolId
        PoolClientId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolClientId
        ShortUUID: !Ref ShortUUID

  # Deploy video workflow
>>>>>>> ef8e22eb9e28d8057d207ce692c76279ca15d5b2:cloudformation/aws-content-analysis-create-new-mie-stack.yaml

  # Deploy Video Workflow
  CompleteVideoWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-video-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowCustomResourceArn"
        OperatorLibraryStack:
<<<<<<< HEAD:cloudformation/aws-content-analysis-use-existing-mie-stack.yaml
          Fn::ImportValue:
            !Sub "${MieStackName}:OperatorLibraryStack"
=======
          Fn::GetAtt:
            - MieStack
            - Outputs.OperatorLibraryStack
        ShortUUID: !Ref ShortUUID
>>>>>>> ef8e22eb9e28d8057d207ce692c76279ca15d5b2:cloudformation/aws-content-analysis-create-new-mie-stack.yaml

  # Deploy image workflow
  CompleteImageWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-image-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowCustomResourceArn"
        OperatorLibraryStack:
<<<<<<< HEAD:cloudformation/aws-content-analysis-use-existing-mie-stack.yaml
          Fn::ImportValue:
            !Sub "${MieStackName}:OperatorLibraryStack"

  ContentAnalysisWebStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-web.template"
      Parameters:
        DataplaneEndpoint:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneApiEndpoint"
        WorkflowEndpoint:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowApiEndpoint"
        ElasticEndpoint: !GetAtt ContentAnalysisElasticsearchStack.Outputs.ElasticEndpoint
        DataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
        UserPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolId
        IdentityPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.IdentityPoolId
        PoolClientId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolClientId
=======
          Fn::GetAtt:
            - MieStack
            - Outputs.OperatorLibraryStack
        ShortUUID: !Ref ShortUUID
>>>>>>> ef8e22eb9e28d8057d207ce692c76279ca15d5b2:cloudformation/aws-content-analysis-create-new-mie-stack.yaml

Outputs:
  CloudfrontUrl:
    Value: !GetAtt ContentAnalysisWebStack.Outputs.CloudfrontUrl
  ElasticEndpoint:
    Value: !GetAtt ContentAnalysisElasticsearchStack.Outputs.ElasticEndpoint
  UserPoolId:
    Value: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolId
  IdentityPoolId:
    Value: !GetAtt ContentAnalysisAuthStack.Outputs.IdentityPoolId
  UserPoolClientId:
    Value: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolClientId
