AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Content Analysis - Deploys the AWS Content Analysis Application

Parameters:
  MieStackName:
    Description: Name of the Media Insights Engine framework stack
    Type: String
  AdminEmail:
    Description: Email address of the Content Analysis Administrator
    Type: String
  ElasticSearchNodeSize:
    Description: "The node type to be provisioned for the Elasticsearch cluster"
    Type: String
    Default: "t2.small.elasticsearch"
    AllowedValues:
      - "t2.small.elasticsearch"
      - "m4.large.elasticsearch"
      - "m4.xlarge.elasticsearch"
      - "c4.large.elasticsearch"
      - "c4.xlarge.elasticsearch"
      - "r4.large.elasticsearch"
      - "r4.xlarge.elasticsearch"

Mappings:
  ContentAnalysisApp:
    SourceCode:
      S3Bucket: "%%BUCKET_NAME%%"
      CodeKeyPrefix: "content-analysis-solution/%%VERSION%%/code"
      TemplateKeyPrefix: "content-analysis-solution/%%VERSION%%/cf"
      WebsitePrefix: "content-analysis-solution/%%VERSION%%/code/website"

Resources:
  # ShortUUID function - create a short UUID to avoid name conflicts
  ShortUUIDFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import string
          import random
          import cfnresponse
          def id_generator(size=6, chars=string.ascii_lowercase + string.digits):
              return "".join(random.choices(chars, k=size))
          def handler(event, context):
              response_data = {'Data': id_generator()}
              cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data, "CustomResourcePhysicalID")
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt ShortUUIDExecutionRole.Arn
  ShortUUIDExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
  ShortUUIDFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt ShortUUIDFunction.Arn
      Principal: 'cloudformation.amazonaws.com'
  GetShortUUID:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !GetAtt ShortUUIDFunction.Arn

  # Deploy everything under the Uuid stack so the resources named with GetShortUUID are all using the same uuid. This lets us reference workflow names from the webapp using a single uuid env variable.

  Uuid:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3.
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-uuid.template"
      Parameters:
        MieStackName: !Ref MieStackName
        S3Bucket: !FindInMap
          - ContentAnalysisApp
          - SourceCode
          - S3Bucket
        CodeKeyPrefix: !FindInMap
          - ContentAnalysisApp
          - SourceCode
          - CodeKeyPrefix
        TemplateKeyPrefix: !FindInMap
          - ContentAnalysisApp
          - SourceCode
          - TemplateKeyPrefix
        WebsitePrefix: !FindInMap
          - ContentAnalysisApp
          - SourceCode
          - WebsitePrefix
        AdminEmail: !Ref AdminEmail
        ElasticSearchNodeSize: !Ref ElasticSearchNodeSize
        ShortUUID: !GetAtt GetShortUUID.Data

Outputs:
  ContentAnalyisSolution:
    Value: !GetAtt Uuid.Outputs.CloudfrontUrl
  ElasticEndpoint:
    Value: !GetAtt Uuid.Outputs.ElasticEndpoint
  UserPoolId:
    Value: !GetAtt Uuid.Outputs.UserPoolId
  IdentityPoolId:
    Value: !GetAtt Uuid.Outputs.IdentityPoolId
  UserPoolClientId:
    Value: !GetAtt Uuid.Outputs.UserPoolClientId
